hexlet-code/core/urls.py
from django.urls import path

from .views import (
        IndexView,
        LoginView,
        LogoutView,
)


urlpatterns = [
  path("", IndexView.as_view(), name="index"),
  path("login/", LoginView.as_view(), name="login"),
  path("logout/", LogoutView.as_view(), name="logout"),
]

hexlet-code/labels/urls.py
from django.urls import path
from .views import (
  LabelListView,
  LabelCreateView,
  LabelUpdateView,
  LabelDeleteView,
)


app_name = "labels"
urlpatterns = [
  path('', LabelListView.as_view(), name="list"),
  path('create/', LabelCreateView.as_view(), name="create"),
  path('<int:pk>/update/', LabelUpdateView.as_view(), name="update"),
  path('<int:pk>/delete/', LabelDeleteView.as_view(), name="delete"),
]

hexlet-code/statuses/urls.py
from django.urls import path
from .views import (
  StatusListView,
  StatusCreateView,
  StatusUpdateView,
  StatusDeleteView,
)


app_name = "statuses"
urlpatterns = [
  path('', StatusListView.as_view(), name="list"),
  path('create/', StatusCreateView.as_view(), name="create"),
  path('<int:pk>/update/', StatusUpdateView.as_view(), name="update"),
  path('<int:pk>/delete/', StatusDeleteView.as_view(), name="delete"),
]

hexlet-code/task_manager/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('statuses/', include('statuses.urls')),
    path('tasks/', include('tasks.urls')),
     path('labels/', include('labels.urls')),
]

hexlet-code/tasks/urls.py
from django.urls import path
from .views import (
  TaskListView,
  TaskDetailView,
  TaskCreateView,
  TaskUpdateView,
  TaskDeleteView,
)


app_name = "tasks"
urlpatterns = [
  path('', TaskListView.as_view(), name="list"),
  path('<int:pk>', TaskDetailView.as_view(), name="task"),
  path('create/', TaskCreateView.as_view(), name="create"),
  path('<int:pk>/update/', TaskUpdateView.as_view(), name="update"),
  path('<int:pk>/delete/', TaskDeleteView.as_view(), name="delete"),
]

hexlet-code/users/urls.py
from django.urls import path
from .views import (
  UserListView,
  UserCreateView,
  UserUpdateView,
  UserDeleteView,
)

app_name = "users"
urlpatterns = [
  path('', UserListView.as_view(), name="list"),
  path('create/', UserCreateView.as_view(), name="create"),
  path('<int:pk>/update/', UserUpdateView.as_view(), name="update"),
  path('<int:pk>/delete/', UserDeleteView.as_view(), name="delete"),
]

hexlet-code/templates/base.html
<!doctype html>
{% load static %}
{% load i18n %}

{% get_current_language as lang %}

<html lang="{{ lang }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Task Manager">
    <title>{% trans 'Task Manager' %} · Hexlet</title>
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    {% block head %}
    {% endblock head %}

  </head>


  <body class="d-flex flex-column min-vh-100">

  <header class="bg-light">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">{% trans 'Task Manager' %}</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'users:list' %}">{% trans 'Users List'%}</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'statuses:list' %}">{% trans 'Statuses' %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tasks:list' %}">{% trans 'Tasks' %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'labels:list' %}">{% trans 'Labels' %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">{% trans 'Logout' %}</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">{% trans 'Sign In' %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:create' %}">{% trans 'Registration' %}</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
  </header>

  {% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}">
             {{ message|safe }}
         </div>
     {% endfor %}
 {% endif %}
{% block content %}

{% endblock content %}

  <footer class="bd-footer py-4 py-md-5 mt-5">
    <div class="inner">
      <p class="text-center">GitHub <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.YyOMn9wj8tZCEyCPTYGlegHaHa%26pid%3DApi&f=1&ipt=f32f908aca62e954fee1552a8130c8bd066526852a4288f3bf749d08c77a4988&ipo=images" width=20px height=20px alt="GitHub">: <a href="https://github.com/StanislavOkopnyi">Stanislav Okopnyi</a></p>
    </div>
  </footer>
</body>
</html>

hexlet-code/templates/index.html
<!doctype html>
{% extends 'base.html' %}

{% block content %}

{% endblock content %}

hexlet-code/templates/login.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<div class="container wrapper flex-grow-1">
    <h1 class="py-4">{% trans 'Login' %}</h1>
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        <p>Your username and password didn't match. Please try again.</p>
    </div>
    {% endif %}
    {% if user.is_authenticated %}
    <div class="alert alert-danger" role="alert">
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    </div>
    {% endif %}
<form method="post" action="{% url 'login' %}">
{% csrf_token %}
{% for field in form %}
        <div class="mb-3">
          {{field.label_tag}}
          {{field}}
        </div>
      {% endfor %}
<input type="submit" value="{% trans 'Login' %}">
</form>
</div>
{# Assumes you set up the password_reset view in your URLconf #}
{# <p><a href="{% url 'password_reset' %}">Lost password?</a></p> #}

{% endblock %}