hexlet-code/core/urls.py
from django.urls import path

from .views import (
        IndexView,
        LoginView,
        LogoutView,
)


urlpatterns = [
  path("", IndexView.as_view(), name="index"),
  path("login/", LoginView.as_view(), name="login"),
  path("logout/", LogoutView.as_view(), name="logout"),
]

hexlet-code/labels/urls.py
from django.urls import path
from .views import (
  LabelListView,
  LabelCreateView,
  LabelUpdateView,
  LabelDeleteView,
)


app_name = "labels"
urlpatterns = [
  path('', LabelListView.as_view(), name="list"),
  path('create/', LabelCreateView.as_view(), name="create"),
  path('<int:pk>/update/', LabelUpdateView.as_view(), name="update"),
  path('<int:pk>/delete/', LabelDeleteView.as_view(), name="delete"),
]

hexlet-code/task_manager/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('statuses/', include('statuses.urls')),
    path('tasks/', include('tasks.urls')),
     path('labels/', include('labels.urls')),
]

hexlet-code/labels/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Label(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("name"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created_at"))

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = _("label")
        verbose_name_plural = _("labels")

hexlet-code/labels/forms.py
from django.forms import ModelForm

from .models import Label


class LabelCreateForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control py-2'

    class Meta:
        model = Label
        fields = ["name", ]


class LabelUpdateForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control py-2'

    class Meta:
        model = Label
        fields = ["name", ]

hexlet-code/labels/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext as _

from .forms import LabelCreateForm, LabelUpdateForm
from .models import Label


class LabelListView(ListView):
    model = Label
    context_object_name = "labels"
    template_name = "labels/index.html"


class LabelCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "labels/create.html"
    form_class = LabelCreateForm
    success_url = reverse_lazy('labels:list')
    success_message = _("Label was created successfully")


class LabelUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = LabelUpdateForm
    template_name = "labels/update.html"
    success_url = reverse_lazy('labels:list')
    success_message = _("Label was updated successfully")
    model = Label


class LabelDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Label
    template_name = "labels/delete.html"
    success_url = reverse_lazy('labels:list')
    success_message = _("Label was deleted successfully")

hexlet-code/templates/labels/create.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
<div class="container wrapper flex-grow-1">
  <h1 class="py-4">{% trans 'Create Label' %}</h1>
  <form action="{% url 'labels:create' %}" method="post">
    {% csrf_token %}
    <div>
      {% for field in form %}
        <div class="mb-3">
          {{field.label_tag}}
          {{field}}
          {{field.errors}}
        </div>
      {% endfor %}
    </div>
  <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}

hexlet-code/templates/labels/delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div>
  <h2>{% trans 'Delete Label' %}</h2>
  <form action="{{ request.path }}" method="post">
    {% csrf_token %}
    <button type="confirm">{% trans 'Delete Label' %}</button>
  </form>
</div>
{% endblock content %}

hexlet-code/templates/labels/index.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
<h2 class="text-center py-2">{% trans 'Labels' %}</h2>
  <div class="container wrapper flex-grow-1">
    <a href="{% url 'labels:create' %}">{% trans 'Create Label'%}</a>
  <table class="table">
    <thead>
    <th>{% trans 'ID' %}</th>
    <th>{% trans 'Name' %}</th>
    <th>{% trans 'Created at' %}</th>
    <th></th>
    </thead>

  <tbody>
    {% for label in labels %}
    <tr>
      <td>{{label.id}}</td>
      <td>{{label.name}}</td>
      <td>{{label.created_at}}</td>
      <td>
          <a href="{% url 'labels:update' pk=label.id %}">{% trans 'Update' %}</a>
        <br>
        <a href="{% url 'labels:delete' pk=label.id %}">{% trans 'Delete' %}</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>

  </table>
  </div>
{% endblock content %}

hexlet-code/templates/labels/update.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
<div class="container wrapper flex-grow-1">
  <h1 class="py-4">{% trans 'Update Label' %}</h1>
  <form action="{{ request.path }}" method="post">
    {% csrf_token %}
    <div>
      {% for field in form %}
        <div class="mb-3">
          {{field.label_tag}}
          {{field}}
          {{field.errors}}
        </div>
      {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
  </form>
</div>
{% endblock content %}