hexlet-code/core/urls.py
from django.urls import path

from .views import (
        IndexView,
        LoginView,
        LogoutView,
)


urlpatterns = [
  path("", IndexView.as_view(), name="index"),
  path("login/", LoginView.as_view(), name="login"),
  path("logout/", LogoutView.as_view(), name="logout"),
]

hexlet-code/task_manager/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('statuses/', include('statuses.urls')),
    path('tasks/', include('tasks.urls')),
     path('labels/', include('labels.urls')),
]

hexlet-code/users/urls.py
from django.urls import path
from .views import (
  UserListView,
  UserCreateView,
  UserUpdateView,
  UserDeleteView,
)

app_name = "users"
urlpatterns = [
  path('', UserListView.as_view(), name="list"),
  path('create/', UserCreateView.as_view(), name="create"),
  path('<int:pk>/update/', UserUpdateView.as_view(), name="update"),
  path('<int:pk>/delete/', UserDeleteView.as_view(), name="delete"),
]

hexlet-code/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    ...

hexlet-code/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

User = get_user_model()


class UserCreateForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control py-2'

    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email"]


class UserUpdateForm(UserChangeForm):
    password = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control py-2'

    class Meta(UserChangeForm.Meta):
        model = User
        fields = ["first_name", "last_name", "username", "email"]

hexlet-code/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import DetailView, ListView, TemplateView
from django.shortcuts import redirect, reverse, render
from django.forms.models import model_to_dict

from .forms import UserCreateForm, UserUpdateForm


User = get_user_model()


class UserListView(ListView):
    model = User
    context_object_name = "users"
    template_name = "users/index.html"


class UserCreateView(TemplateView):
    template_name = "users/create.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = UserCreateForm
        return context

    def post(self, request):
        form = UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("login"), permanent=True)
        return render(request, self.template_name, context={"form": form})


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = User
    template_name = "users/update.html"

    def test_func(self):
        user = self.get_object()
        return user == self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        form = UserUpdateForm(model_to_dict(user))
        context["form"] = form
        return context

    def post(self, request, *args, **kwargs):
        user = self.get_object()
        form = UserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect(reverse("users:list"), permanent=True)
        return render(request, self.template_name, context={"form": form})


class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = User
    template_name = "users/delete.html"

    def test_func(self):
        user = self.get_object()
        return user == self.request.user

    def post(self, request, *args, **kwargs):
        user = self.get_object()
        user.delete()
        return redirect(reverse("users:list"), permanent=True)

hexlet-code/templates/users/create.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
<div class="container wrapper flex-grow-1">
  <h1 class="py-4">{% trans 'Create User' %}</h2>
  <form action="{% url 'users:create' %}" method="post">
    {% csrf_token %}
    <div>
      {% for field in form %}
        <div class="mb-3">
          {{field.label_tag}}
          {{field}}
          {{field.errors}}
        </div>
      {% endfor %}
    </div>
  <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}

hexlet-code/templates/users/delete.html
{% extends 'base.html' %}


{% block content %}
<div>
  <h2>Delete User</h2>
  <form action="{{ request.path }}" method="post">
    {% csrf_token %}
    <button type="confirm">Delete User</button>
  </form>
</div>
{% endblock content %}

hexlet-code/templates/users/index.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
<h2 class="text-center py-2">{% trans 'Users' %}</h2>
  <div class="container wrapper flex-grow-1">
  <table class="table">
    <thead>
    <th>{% trans 'ID' %}</th>
    <th>{% trans 'Username' %}</th>
    <th>{% trans 'Fullname' %}</th>
    <th>{% trans 'Date joined' %}</th>
    <th></th>
    </thead>

  <tbody>
    {% for user in users %}
    <tr>
      <td>{{user.id}}</td>
      <td>{{user.username}}</td>
      <td>{{user.get_full_name}}</td>
      <td>{{user.date_joined}}</td>
      <td>
          <a href="{% url 'users:update' pk=user.id %}">{% trans 'Update' %}</a>
        <br>
        <a href="{% url 'users:delete' pk=user.id %}">{% trans 'Delete' %}</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>

  </table>
  </div>
{% endblock content %}

hexlet-code/templates/users/update.html
{% extends 'base.html' %}


{% block content %}
<div class="container wrapper flex-grow-1">
  <h1 class="py-4">Update User</h1>
  <form action="{{ request.path }}" method="post">
    {% csrf_token %}
    <div>
      {% for field in form %}
        <div class="mb-3">
          {{field.label_tag}}
          {{field}}
          {{field.errors}}
        </div>
      {% endfor %}
    </div>
  <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}