hexlet-code/core/urls.py
from django.urls import path

from .views import (
        IndexView,
        LoginView,
        LogoutView,
)


urlpatterns = [
  path("", IndexView.as_view(), name="index"),
  path("login/", LoginView.as_view(), name="login"),
  path("logout/", LogoutView.as_view(), name="logout"),
]

hexlet-code/task_manager/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('statuses/', include('statuses.urls')),
    path('tasks/', include('tasks.urls')),
     path('labels/', include('labels.urls')),
]

hexlet-code/tasks/urls.py
from django.urls import path
from .views import (
  TaskListView,
  TaskDetailView,
  TaskCreateView,
  TaskUpdateView,
  TaskDeleteView,
)


app_name = "tasks"
urlpatterns = [
  path('', TaskListView.as_view(), name="list"),
  path('<int:pk>', TaskDetailView.as_view(), name="task"),
  path('create/', TaskCreateView.as_view(), name="create"),
  path('<int:pk>/update/', TaskUpdateView.as_view(), name="update"),
  path('<int:pk>/delete/', TaskDeleteView.as_view(), name="delete"),
]

hexlet-code/tasks/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from statuses.models import Status
from labels.models import Label

User = get_user_model()


class Task(models.Model):

    author = models.ForeignKey(User, on_delete=models.RESTRICT, related_name="created_tasks", verbose_name=_("author"))
    status = models.ForeignKey(Status, on_delete=models.RESTRICT, verbose_name=_("status"))
    performer = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="todo_tasks", verbose_name=_("performer"))
    labels = models.ManyToManyField(Label, verbose_name=_("labels"))
    name = models.CharField(max_length=255, verbose_name=_("name"))
    text = models.TextField(verbose_name=_("text"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created_at"))

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = _("task")
        verbose_name_plural = _("tasks")

hexlet-code/tasks/forms.py
from django.forms import ModelForm, ModelMultipleChoiceField

from .models import Task


class TaskCreateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control py-2'

    class Meta:
        model = Task
        fields = "__all__"


class TaskUpdateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control py-2'

    class Meta:
        model = Task
        exclude = ["author"]

hexlet-code/tasks/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import CreateView, DetailView, UpdateView, ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext as _

from .filters import TaskFilter
from .forms import TaskCreateForm, TaskUpdateForm
from .models import Task


class TaskListView(ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "tasks/index.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data(object_list=object_list, **kwargs)
        filter = TaskFilter(self.request.GET, queryset=Task.objects.all())
        data["filter"] = filter
        return data


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = "tasks/task.html"


class TaskCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "tasks/create.html"
    form_class = TaskCreateForm
    success_url = reverse_lazy('tasks:list')
    success_message = _("Task was created successfully")


class TaskUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = TaskUpdateForm
    template_name = "tasks/update.html"
    success_url = reverse_lazy('tasks:list')
    success_message = _("Task was updated successfully")
    model = Task


class TaskDeleteView(LoginRequiredMixin, UserPassesTestMixin,
                     SuccessMessageMixin, DeleteView):
    model = Task
    template_name = "tasks/delete.html"
    success_url = reverse_lazy('tasks:list')
    success_message = _("Task was deleted successfully")

    def test_func(self):
        return self.request.user == self.get_object().author

hexlet-code/templates/tasks/create.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
<div class="container wrapper flex-grow-1">
  <h1 class="py-4">{% trans 'Create Task' %}</h2>
  <form action="{% url 'tasks:create' %}" method="post">
    {% csrf_token %}
    <div>
      {% for field in form %}
        <div class="mb-3">
          {{field.label_tag}}
          {{field}}
          {{field.errors}}
        </div>
      {% endfor %}
    </div>
  <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}

hexlet-code/templates/tasks/delete.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
<div>
  <h2>{% trans 'Delete Task' %}</h2>
  <form action="{{ request.path }}" method="post">
    {% csrf_token %}
    <button type="confirm">{% trans 'Delete Task' %}</button>
  </form>
</div>
{% endblock content %}

hexlet-code/templates/tasks/index.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
  <div class="container wrapper flex-grow-1">
  <h2 class="py-2 my-4">{% trans 'Tasks' %}</h2>
  <a class="btn btn-primary mb-3" href="{% url 'tasks:create' %}">{% trans 'Create task'%}</a>
  <div class="card mb-3">
  <div class="card-body bg-light">
  <form class="form-inline center" method="get">
        {{ filter.form.as_p }}
  <input class="btn btn-primary" type="submit" value="{% trans 'Show' %}" />
  </form>
  </div>
  </div>
  <table class="table">
    <thead>
    <th>{% trans 'ID' %}</th>
    <th>{% trans 'Name' %}</th>
    <th>{% trans 'Status' %}</th>
    <th>{% trans 'Performer' %}</th>
    <th>{% trans 'Created at' %}</th>
    <th></th>
    </thead>

  <tbody>
    {% if filter.qs != None %}
    {% for task in filter.qs %}
    <tr>
      <td><a href="{% url 'tasks:task' pk=task.id %}">{{task.id}}</td>
      <td>{{task.name}}</td>
      <td>{{task.status}}</td>
      <td>{{task.performer}}</td>
      <td>{{task.created_at}}</td>
      <td>
          <a href="{% url 'tasks:update' pk=task.id %}">{% trans 'Update' %}</a>
        <br>
        <a href="{% url 'tasks:delete' pk=task.id %}">{% trans 'Delete' %}</a>
      </td>
    </tr>
    {% endfor %}
    {% else %}
    {% for task in tasks %}
    <tr>
      <td><a href="{% url 'tasks:task' pk=task.id %}">{{task.id}}</td>
      <td>{{task.name}}</td>
      <td>{{task.status}}</td>
      <td>{{task.performer}}</td>
      <td>{{task.created_at}}</td>
      <td>
          <a href="{% url 'tasks:update' pk=task.id %}">{% trans 'Update' %}</a>
        <br>
        <a href="{% url 'tasks:delete' pk=task.id %}">{% trans 'Delete' %}</a>
      </td>
    </tr>
    {% endfor %}
    {% endif %}
  </tbody>

  </table>
  </div>
{% endblock content %}

hexlet-code/templates/tasks/task.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
<div class="container wrapper flex-grow-1">
  <h1 class="my-4">
      {% trans 'Task View' %}
  </h1>

<div class="card">
  <div class="card-header bg-secondary text-white">
    <h2>{{ object.name }}</h2>
  </div>
  <div class="card-body bg-light">
    <p>{{ object.text }}</p>
    <hr>
    <div class="container">
      <div class="row p-1">
        <div class="col">{% trans 'Author' %}</div>
        <div class="col">{{ object.author }}</div>
      </div>
      <div class="row p-1">
        <div class="col">{% trans 'Performer' %}</div>
        <div class="col">{{ object.performer }}</div>
      </div>
      <div class="row p-1">
        <div class="col">{% trans 'Status' %}</div>
        <div class="col">{{ object.status }}</div>
      </div>
      <div class="row p-1">
        <div class="col">{% trans 'Created at' %}</div>
        <div class="col">{{ object.created_at }}</div>
      </div>
      <div class="row p-1">
        <div class="col">
          <h6>{% trans 'Labels:' %}</h6>
          <ul>
            {% for label in object.labels.all %}
              <li>{{ label }}</li>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div class="row p-1">
        <div class="col">
          <a href="{% url 'tasks:update' pk=object.id %}">{% trans 'Update' %}</a>
          <br>
          <a href="{% url 'tasks:delete' pk=object.id %}">{% trans 'Delete' %}</a>
        </div>
      </div>
    </div>
  </div>
</div>

</div>
{% endblock %}

hexlet-code/templates/tasks/update.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
<div class="container wrapper flex-grow-1">
  <h1 class="py-4">{% trans 'Update User' %}</h1>
  <form action="{{ request.path }}" method="post">
    {% csrf_token %}
    <div>
      {% for field in form %}
        <div class="mb-3">
          {{field.label_tag}}
          {{field}}
          {{field.errors}}
        </div>
      {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
  </form>
</div>
{% endblock content %}